# This workflow will publish the .NET template on release publish
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# See also: https://docs.github.com/en/actions/tutorials/build-and-test-code/net#publishing-to-package-registries

name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore project
        run: dotnet restore
      - name: Create the package
        run: dotnet pack --no-build --configuration Release BoboBayPluginTemplate
      - name: Publish the package to AetharNet NuGet Feed
        run: dotnet nuget push -s "https://nuget.aethar.net/v3/index.json" -k "${{secrets.NUGET_AUTH_TOKEN}}" BoboBayPluginTemplate/bin/Release/*.nupkg
